[35mDEBUG   [0m faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.address`.
[35mDEBUG   [0m faker.factory:factory.py:95 Provider `faker.providers.address` has been localized to `en_US`.
[35mDEBUG   [0m faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.automotive`.
[35mDEBUG   [0m faker.factory:factory.py:95 Provider `faker.providers.automotive` has been localized to `en_US`.
[35mDEBUG   [0m faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.bank`.
[35mDEBUG   [0m faker.factory:factory.py:86 Specified locale `en_US` is not available for provider `faker.providers.bank`. Locale reset to `en_GB` for this provider.
[35mDEBUG   [0m faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.barcode`.
[35mDEBUG   [0m faker.factory:factory.py:95 Provider `faker.providers.barcode` has been localized to `en_US`.
[35mDEBUG   [0m faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.color`.
[35mDEBUG   [0m faker.factory:factory.py:95 Provider `faker.providers.color` has been localized to `en_US`.
[35mDEBUG   [0m faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.company`.
[35mDEBUG   [0m faker.factory:factory.py:95 Provider `faker.providers.company` has been localized to `en_US`.
[35mDEBUG   [0m faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.credit_card`.
[35mDEBUG   [0m faker.factory:factory.py:95 Provider `faker.providers.credit_card` has been localized to `en_US`.
[35mDEBUG   [0m faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.currency`.
[35mDEBUG   [0m faker.factory:factory.py:95 Provider `faker.providers.currency` has been localized to `en_US`.
[35mDEBUG   [0m faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.date_time`.
[35mDEBUG   [0m faker.factory:factory.py:95 Provider `faker.providers.date_time` has been localized to `en_US`.
[35mDEBUG   [0m faker.factory:factory.py:106 Provider `faker.providers.emoji` does not feature localization. Specified locale `en_US` is not utilized for this provider.
[35mDEBUG   [0m faker.factory:factory.py:106 Provider `faker.providers.file` does not feature localization. Specified locale `en_US` is not utilized for this provider.
[35mDEBUG   [0m faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.geo`.
[35mDEBUG   [0m faker.factory:factory.py:95 Provider `faker.providers.geo` has been localized to `en_US`.
[35mDEBUG   [0m faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.internet`.
[35mDEBUG   [0m faker.factory:factory.py:95 Provider `faker.providers.internet` has been localized to `en_US`.
[35mDEBUG   [0m faker.factory:factory.py:106 Provider `faker.providers.isbn` does not feature localization. Specified locale `en_US` is not utilized for this provider.
[35mDEBUG   [0m faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.job`.
[35mDEBUG   [0m faker.factory:factory.py:95 Provider `faker.providers.job` has been localized to `en_US`.
[35mDEBUG   [0m faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.lorem`.
[35mDEBUG   [0m faker.factory:factory.py:95 Provider `faker.providers.lorem` has been localized to `en_US`.
[35mDEBUG   [0m faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.misc`.
[35mDEBUG   [0m faker.factory:factory.py:95 Provider `faker.providers.misc` has been localized to `en_US`.
[35mDEBUG   [0m faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.passport`.
[35mDEBUG   [0m faker.factory:factory.py:95 Provider `faker.providers.passport` has been localized to `en_US`.
[35mDEBUG   [0m faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.person`.
[35mDEBUG   [0m faker.factory:factory.py:95 Provider `faker.providers.person` has been localized to `en_US`.
[35mDEBUG   [0m faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.phone_number`.
[35mDEBUG   [0m faker.factory:factory.py:95 Provider `faker.providers.phone_number` has been localized to `en_US`.
[35mDEBUG   [0m faker.factory:factory.py:106 Provider `faker.providers.profile` does not feature localization. Specified locale `en_US` is not utilized for this provider.
[35mDEBUG   [0m faker.factory:factory.py:106 Provider `faker.providers.python` does not feature localization. Specified locale `en_US` is not utilized for this provider.
[35mDEBUG   [0m faker.factory:factory.py:106 Provider `faker.providers.sbn` does not feature localization. Specified locale `en_US` is not utilized for this provider.
[35mDEBUG   [0m faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.ssn`.
[35mDEBUG   [0m faker.factory:factory.py:95 Provider `faker.providers.ssn` has been localized to `en_US`.
[35mDEBUG   [0m faker.factory:factory.py:106 Provider `faker.providers.user_agent` does not feature localization. Specified locale `en_US` is not utilized for this provider.
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 2] Max packet in: 32768 bytes
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 2] Max packet out: 32768 bytes
[35mDEBUG   [0m paramiko.transport:transport.py:1893 Secsh channel 2 opened.
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 2] Sesch channel 2 request ok
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 2] EOF received (2)
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 2] EOF sent (2)
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 3] Max packet in: 32768 bytes
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 3] Max packet out: 32768 bytes
[35mDEBUG   [0m paramiko.transport:transport.py:1893 Secsh channel 3 opened.
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 3] Sesch channel 3 request ok
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 3] EOF received (3)
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 3] EOF sent (3)
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 4] Max packet in: 32768 bytes
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 4] Max packet out: 32768 bytes
[35mDEBUG   [0m paramiko.transport:transport.py:1893 Secsh channel 4 opened.
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 4] Sesch channel 4 request ok
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 4] EOF received (4)
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 4] EOF sent (4)
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 5] Max packet in: 32768 bytes
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 5] Max packet out: 32768 bytes
[35mDEBUG   [0m paramiko.transport:transport.py:1893 Secsh channel 5 opened.
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 5] Sesch channel 5 request ok
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 5] EOF received (5)
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 5] EOF sent (5)
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 6] Max packet in: 32768 bytes
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 6] Max packet out: 32768 bytes
[35mDEBUG   [0m paramiko.transport:transport.py:1893 Secsh channel 6 opened.
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 6] Sesch channel 6 request ok
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 6] EOF received (6)
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 6] EOF sent (6)
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 7] Max packet in: 32768 bytes
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 7] Max packet out: 32768 bytes
[35mDEBUG   [0m paramiko.transport:transport.py:1893 Secsh channel 7 opened.
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 7] Sesch channel 7 request ok
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 7] EOF received (7)
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 7] EOF sent (7)
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 8] Max packet in: 32768 bytes
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 8] Max packet out: 32768 bytes
[35mDEBUG   [0m paramiko.transport:transport.py:1893 Secsh channel 8 opened.
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 8] Sesch channel 8 request ok
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 8] EOF received (8)
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 8] EOF sent (8)
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 9] Max packet in: 32768 bytes
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 10] Max packet in: 32768 bytes
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 9] Max packet out: 32768 bytes
[35mDEBUG   [0m paramiko.transport:transport.py:1893 Secsh channel 9 opened.
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 10] Max packet out: 32768 bytes
[35mDEBUG   [0m paramiko.transport:transport.py:1893 Secsh channel 10 opened.
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 9] Sesch channel 9 request ok
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 10] Sesch channel 10 request ok
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 10] EOF received (10)
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 10] EOF sent (10)
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 9] EOF received (9)
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 9] EOF sent (9)
[35mDEBUG   [0m httpcore.connection:_trace.py:45 connect_tcp.started host='192.168.0.207' port=1317 local_address=None timeout=10 socket_options=None
[35mDEBUG   [0m httpcore.connection:_trace.py:45 connect_tcp.started host='192.168.0.207' port=1317 local_address=None timeout=10 socket_options=None
[35mDEBUG   [0m httpcore.connection:_trace.py:45 connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x7fad245004c0>
[35mDEBUG   [0m httpcore.http11:_trace.py:45 send_request_headers.started request=<Request [b'GET']>
[35mDEBUG   [0m httpcore.connection:_trace.py:45 connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x7fad24500c40>
[35mDEBUG   [0m httpcore.http11:_trace.py:45 send_request_headers.complete
[35mDEBUG   [0m httpcore.http11:_trace.py:45 send_request_headers.started request=<Request [b'GET']>
[35mDEBUG   [0m httpcore.http11:_trace.py:45 send_request_body.started request=<Request [b'GET']>
[35mDEBUG   [0m httpcore.http11:_trace.py:45 send_request_body.complete
[35mDEBUG   [0m httpcore.http11:_trace.py:45 send_request_headers.complete
[35mDEBUG   [0m httpcore.http11:_trace.py:45 receive_response_headers.started request=<Request [b'GET']>
[35mDEBUG   [0m httpcore.http11:_trace.py:45 send_request_body.started request=<Request [b'GET']>
[35mDEBUG   [0m httpcore.http11:_trace.py:45 send_request_body.complete
[35mDEBUG   [0m httpcore.http11:_trace.py:45 receive_response_headers.started request=<Request [b'GET']>
[35mDEBUG   [0m httpcore.http11:_trace.py:45 receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'application/json'), (b'Grpc-Metadata-Content-Type', b'application/grpc+cosmos-sdk-grpc-codec'), (b'Grpc-Metadata-X-Cosmos-Block-Height', b'65333'), (b'X-Server-Time', b'1693278250'), (b'Date', b'Tue, 29 Aug 2023 03:04:10 GMT'), (b'Content-Length', b'114')])
[35mDEBUG   [0m httpcore.http11:_trace.py:45 receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'application/json'), (b'Grpc-Metadata-Content-Type', b'application/grpc+cosmos-sdk-grpc-codec'), (b'Grpc-Metadata-X-Cosmos-Block-Height', b'65333'), (b'X-Server-Time', b'1693278250'), (b'Date', b'Tue, 29 Aug 2023 03:04:10 GMT'), (b'Transfer-Encoding', b'chunked')])
[32mINFO    [0m httpx:_client.py:1013 HTTP Request: GET http://192.168.0.207:1317/cosmos/tx/v1beta1/txs/A17F5538B86F7A86EB69B7971342E2489CD04DC8633275F2315CDEDBE1E4DE09 "HTTP/1.1 404 Not Found"
[32mINFO    [0m httpx:_client.py:1013 HTTP Request: GET http://192.168.0.207:1317/cosmos/tx/v1beta1/txs/FDE86C1A0DD26E9A22E2BF212ABDC731ED8F2F65C152B12BC522B4D6B800327F "HTTP/1.1 200 OK"
[35mDEBUG   [0m httpcore.http11:_trace.py:45 receive_response_body.started request=<Request [b'GET']>
[35mDEBUG   [0m httpcore.http11:_trace.py:45 receive_response_body.started request=<Request [b'GET']>
[35mDEBUG   [0m httpcore.http11:_trace.py:45 receive_response_body.complete
[35mDEBUG   [0m httpcore.http11:_trace.py:45 receive_response_body.complete
[35mDEBUG   [0m httpcore.http11:_trace.py:45 response_closed.started
[35mDEBUG   [0m httpcore.http11:_trace.py:45 response_closed.started
[35mDEBUG   [0m httpcore.http11:_trace.py:45 response_closed.complete
[35mDEBUG   [0m httpcore.http11:_trace.py:45 response_closed.complete
[35mDEBUG   [0m httpcore.http11:_trace.py:45 send_request_headers.started request=<Request [b'GET']>
[35mDEBUG   [0m httpcore.http11:_trace.py:45 send_request_headers.complete
[35mDEBUG   [0m httpcore.http11:_trace.py:45 send_request_body.started request=<Request [b'GET']>
[35mDEBUG   [0m httpcore.http11:_trace.py:45 send_request_body.complete
[35mDEBUG   [0m httpcore.http11:_trace.py:45 receive_response_headers.started request=<Request [b'GET']>
[35mDEBUG   [0m httpcore.http11:_trace.py:45 receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'application/json'), (b'Grpc-Metadata-Content-Type', b'application/grpc+cosmos-sdk-grpc-codec'), (b'Grpc-Metadata-X-Cosmos-Block-Height', b'65334'), (b'X-Server-Time', b'1693278253'), (b'Date', b'Tue, 29 Aug 2023 03:04:13 GMT'), (b'Content-Length', b'114')])
[32mINFO    [0m httpx:_client.py:1013 HTTP Request: GET http://192.168.0.207:1317/cosmos/tx/v1beta1/txs/A17F5538B86F7A86EB69B7971342E2489CD04DC8633275F2315CDEDBE1E4DE09 "HTTP/1.1 404 Not Found"
[35mDEBUG   [0m httpcore.http11:_trace.py:45 receive_response_body.started request=<Request [b'GET']>
[35mDEBUG   [0m httpcore.http11:_trace.py:45 receive_response_body.complete
[35mDEBUG   [0m httpcore.http11:_trace.py:45 response_closed.started
[35mDEBUG   [0m httpcore.http11:_trace.py:45 response_closed.complete
[35mDEBUG   [0m httpcore.connection:_trace.py:45 close.started
[35mDEBUG   [0m httpcore.connection:_trace.py:45 close.complete
[35mDEBUG   [0m httpcore.http11:_trace.py:45 send_request_headers.started request=<Request [b'GET']>
[35mDEBUG   [0m httpcore.http11:_trace.py:45 send_request_headers.complete
[35mDEBUG   [0m httpcore.http11:_trace.py:45 send_request_body.started request=<Request [b'GET']>
[35mDEBUG   [0m httpcore.http11:_trace.py:45 send_request_body.complete
[35mDEBUG   [0m httpcore.http11:_trace.py:45 receive_response_headers.started request=<Request [b'GET']>
[35mDEBUG   [0m httpcore.http11:_trace.py:45 receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'application/json'), (b'Grpc-Metadata-Content-Type', b'application/grpc+cosmos-sdk-grpc-codec'), (b'Grpc-Metadata-X-Cosmos-Block-Height', b'65335'), (b'X-Server-Time', b'1693278256'), (b'Date', b'Tue, 29 Aug 2023 03:04:16 GMT'), (b'Content-Length', b'114')])
[32mINFO    [0m httpx:_client.py:1013 HTTP Request: GET http://192.168.0.207:1317/cosmos/tx/v1beta1/txs/A17F5538B86F7A86EB69B7971342E2489CD04DC8633275F2315CDEDBE1E4DE09 "HTTP/1.1 404 Not Found"
[35mDEBUG   [0m httpcore.http11:_trace.py:45 receive_response_body.started request=<Request [b'GET']>
[35mDEBUG   [0m httpcore.http11:_trace.py:45 receive_response_body.complete
[35mDEBUG   [0m httpcore.http11:_trace.py:45 response_closed.started
[35mDEBUG   [0m httpcore.http11:_trace.py:45 response_closed.complete
[35mDEBUG   [0m httpcore.http11:_trace.py:45 send_request_headers.started request=<Request [b'GET']>
[35mDEBUG   [0m httpcore.http11:_trace.py:45 send_request_headers.complete
[35mDEBUG   [0m httpcore.http11:_trace.py:45 send_request_body.started request=<Request [b'GET']>
[35mDEBUG   [0m httpcore.http11:_trace.py:45 send_request_body.complete
[35mDEBUG   [0m httpcore.http11:_trace.py:45 receive_response_headers.started request=<Request [b'GET']>
[35mDEBUG   [0m httpcore.http11:_trace.py:45 receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'application/json'), (b'Grpc-Metadata-Content-Type', b'application/grpc+cosmos-sdk-grpc-codec'), (b'Grpc-Metadata-X-Cosmos-Block-Height', b'65335'), (b'X-Server-Time', b'1693278260'), (b'Date', b'Tue, 29 Aug 2023 03:04:20 GMT'), (b'Content-Length', b'114')])
[32mINFO    [0m httpx:_client.py:1013 HTTP Request: GET http://192.168.0.207:1317/cosmos/tx/v1beta1/txs/A17F5538B86F7A86EB69B7971342E2489CD04DC8633275F2315CDEDBE1E4DE09 "HTTP/1.1 404 Not Found"
[35mDEBUG   [0m httpcore.http11:_trace.py:45 receive_response_body.started request=<Request [b'GET']>
[35mDEBUG   [0m httpcore.http11:_trace.py:45 receive_response_body.complete
[35mDEBUG   [0m httpcore.http11:_trace.py:45 response_closed.started
[35mDEBUG   [0m httpcore.http11:_trace.py:45 response_closed.complete
[35mDEBUG   [0m httpcore.http11:_trace.py:45 send_request_headers.started request=<Request [b'GET']>
[35mDEBUG   [0m httpcore.http11:_trace.py:45 send_request_headers.complete
[35mDEBUG   [0m httpcore.http11:_trace.py:45 send_request_body.started request=<Request [b'GET']>
[35mDEBUG   [0m httpcore.http11:_trace.py:45 send_request_body.complete
[35mDEBUG   [0m httpcore.http11:_trace.py:45 receive_response_headers.started request=<Request [b'GET']>
[35mDEBUG   [0m httpcore.http11:_trace.py:45 receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'application/json'), (b'Grpc-Metadata-Content-Type', b'application/grpc+cosmos-sdk-grpc-codec'), (b'Grpc-Metadata-X-Cosmos-Block-Height', b'65336'), (b'X-Server-Time', b'1693278263'), (b'Date', b'Tue, 29 Aug 2023 03:04:23 GMT'), (b'Content-Length', b'114')])
[32mINFO    [0m httpx:_client.py:1013 HTTP Request: GET http://192.168.0.207:1317/cosmos/tx/v1beta1/txs/A17F5538B86F7A86EB69B7971342E2489CD04DC8633275F2315CDEDBE1E4DE09 "HTTP/1.1 404 Not Found"
[35mDEBUG   [0m httpcore.http11:_trace.py:45 receive_response_body.started request=<Request [b'GET']>
[35mDEBUG   [0m httpcore.http11:_trace.py:45 receive_response_body.complete
[35mDEBUG   [0m httpcore.http11:_trace.py:45 response_closed.started
[35mDEBUG   [0m httpcore.http11:_trace.py:45 response_closed.complete
[35mDEBUG   [0m httpcore.http11:_trace.py:45 send_request_headers.started request=<Request [b'GET']>
[35mDEBUG   [0m httpcore.http11:_trace.py:45 send_request_headers.complete
[35mDEBUG   [0m httpcore.http11:_trace.py:45 send_request_body.started request=<Request [b'GET']>
[35mDEBUG   [0m httpcore.http11:_trace.py:45 send_request_body.complete
[35mDEBUG   [0m httpcore.http11:_trace.py:45 receive_response_headers.started request=<Request [b'GET']>
[35mDEBUG   [0m httpcore.http11:_trace.py:45 receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'application/json'), (b'Grpc-Metadata-Content-Type', b'application/grpc+cosmos-sdk-grpc-codec'), (b'Grpc-Metadata-X-Cosmos-Block-Height', b'65336'), (b'X-Server-Time', b'1693278266'), (b'Date', b'Tue, 29 Aug 2023 03:04:26 GMT'), (b'Content-Length', b'114')])
[32mINFO    [0m httpx:_client.py:1013 HTTP Request: GET http://192.168.0.207:1317/cosmos/tx/v1beta1/txs/A17F5538B86F7A86EB69B7971342E2489CD04DC8633275F2315CDEDBE1E4DE09 "HTTP/1.1 404 Not Found"
[35mDEBUG   [0m httpcore.http11:_trace.py:45 receive_response_body.started request=<Request [b'GET']>
[35mDEBUG   [0m httpcore.http11:_trace.py:45 receive_response_body.complete
[35mDEBUG   [0m httpcore.http11:_trace.py:45 response_closed.started
[35mDEBUG   [0m httpcore.http11:_trace.py:45 response_closed.complete
[35mDEBUG   [0m httpcore.http11:_trace.py:45 send_request_headers.started request=<Request [b'GET']>
[35mDEBUG   [0m httpcore.http11:_trace.py:45 send_request_headers.complete
[35mDEBUG   [0m httpcore.http11:_trace.py:45 send_request_body.started request=<Request [b'GET']>
[35mDEBUG   [0m httpcore.http11:_trace.py:45 send_request_body.complete
[35mDEBUG   [0m httpcore.http11:_trace.py:45 receive_response_headers.started request=<Request [b'GET']>
[35mDEBUG   [0m httpcore.http11:_trace.py:45 receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'application/json'), (b'Grpc-Metadata-Content-Type', b'application/grpc+cosmos-sdk-grpc-codec'), (b'Grpc-Metadata-X-Cosmos-Block-Height', b'65337'), (b'X-Server-Time', b'1693278269'), (b'Date', b'Tue, 29 Aug 2023 03:04:29 GMT'), (b'Content-Length', b'114')])
[32mINFO    [0m httpx:_client.py:1013 HTTP Request: GET http://192.168.0.207:1317/cosmos/tx/v1beta1/txs/A17F5538B86F7A86EB69B7971342E2489CD04DC8633275F2315CDEDBE1E4DE09 "HTTP/1.1 404 Not Found"
[35mDEBUG   [0m httpcore.http11:_trace.py:45 receive_response_body.started request=<Request [b'GET']>
[35mDEBUG   [0m httpcore.http11:_trace.py:45 receive_response_body.complete
[35mDEBUG   [0m httpcore.http11:_trace.py:45 response_closed.started
[35mDEBUG   [0m httpcore.http11:_trace.py:45 response_closed.complete
[35mDEBUG   [0m httpcore.http11:_trace.py:45 send_request_headers.started request=<Request [b'GET']>
[35mDEBUG   [0m httpcore.http11:_trace.py:45 send_request_headers.complete
[35mDEBUG   [0m httpcore.http11:_trace.py:45 send_request_body.started request=<Request [b'GET']>
[35mDEBUG   [0m httpcore.http11:_trace.py:45 send_request_body.complete
[35mDEBUG   [0m httpcore.http11:_trace.py:45 receive_response_headers.started request=<Request [b'GET']>
[35mDEBUG   [0m httpcore.http11:_trace.py:45 receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'application/json'), (b'Grpc-Metadata-Content-Type', b'application/grpc+cosmos-sdk-grpc-codec'), (b'Grpc-Metadata-X-Cosmos-Block-Height', b'65338'), (b'X-Server-Time', b'1693278272'), (b'Date', b'Tue, 29 Aug 2023 03:04:32 GMT'), (b'Content-Length', b'114')])
[32mINFO    [0m httpx:_client.py:1013 HTTP Request: GET http://192.168.0.207:1317/cosmos/tx/v1beta1/txs/A17F5538B86F7A86EB69B7971342E2489CD04DC8633275F2315CDEDBE1E4DE09 "HTTP/1.1 404 Not Found"
[35mDEBUG   [0m httpcore.http11:_trace.py:45 receive_response_body.started request=<Request [b'GET']>
[35mDEBUG   [0m httpcore.http11:_trace.py:45 receive_response_body.complete
[35mDEBUG   [0m httpcore.http11:_trace.py:45 response_closed.started
[35mDEBUG   [0m httpcore.http11:_trace.py:45 response_closed.complete
[35mDEBUG   [0m httpcore.http11:_trace.py:45 send_request_headers.started request=<Request [b'GET']>
[35mDEBUG   [0m httpcore.http11:_trace.py:45 send_request_headers.complete
[35mDEBUG   [0m httpcore.http11:_trace.py:45 send_request_body.started request=<Request [b'GET']>
[35mDEBUG   [0m httpcore.http11:_trace.py:45 send_request_body.complete
[35mDEBUG   [0m httpcore.http11:_trace.py:45 receive_response_headers.started request=<Request [b'GET']>
[35mDEBUG   [0m httpcore.http11:_trace.py:45 receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'application/json'), (b'Grpc-Metadata-Content-Type', b'application/grpc+cosmos-sdk-grpc-codec'), (b'Grpc-Metadata-X-Cosmos-Block-Height', b'65338'), (b'X-Server-Time', b'1693278275'), (b'Date', b'Tue, 29 Aug 2023 03:04:35 GMT'), (b'Content-Length', b'114')])
[32mINFO    [0m httpx:_client.py:1013 HTTP Request: GET http://192.168.0.207:1317/cosmos/tx/v1beta1/txs/A17F5538B86F7A86EB69B7971342E2489CD04DC8633275F2315CDEDBE1E4DE09 "HTTP/1.1 404 Not Found"
[35mDEBUG   [0m httpcore.http11:_trace.py:45 receive_response_body.started request=<Request [b'GET']>
[35mDEBUG   [0m httpcore.http11:_trace.py:45 receive_response_body.complete
[35mDEBUG   [0m httpcore.http11:_trace.py:45 response_closed.started
[35mDEBUG   [0m httpcore.http11:_trace.py:45 response_closed.complete
[35mDEBUG   [0m httpcore.http11:_trace.py:45 send_request_headers.started request=<Request [b'GET']>
[35mDEBUG   [0m httpcore.http11:_trace.py:45 send_request_headers.complete
[35mDEBUG   [0m httpcore.http11:_trace.py:45 send_request_body.started request=<Request [b'GET']>
[35mDEBUG   [0m httpcore.http11:_trace.py:45 send_request_body.complete
[35mDEBUG   [0m httpcore.http11:_trace.py:45 receive_response_headers.started request=<Request [b'GET']>
[35mDEBUG   [0m httpcore.http11:_trace.py:45 receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'application/json'), (b'Grpc-Metadata-Content-Type', b'application/grpc+cosmos-sdk-grpc-codec'), (b'Grpc-Metadata-X-Cosmos-Block-Height', b'65339'), (b'X-Server-Time', b'1693278278'), (b'Date', b'Tue, 29 Aug 2023 03:04:38 GMT'), (b'Content-Length', b'114')])
[32mINFO    [0m httpx:_client.py:1013 HTTP Request: GET http://192.168.0.207:1317/cosmos/tx/v1beta1/txs/A17F5538B86F7A86EB69B7971342E2489CD04DC8633275F2315CDEDBE1E4DE09 "HTTP/1.1 404 Not Found"
[35mDEBUG   [0m httpcore.http11:_trace.py:45 receive_response_body.started request=<Request [b'GET']>
[35mDEBUG   [0m httpcore.http11:_trace.py:45 receive_response_body.complete
[35mDEBUG   [0m httpcore.http11:_trace.py:45 response_closed.started
[35mDEBUG   [0m httpcore.http11:_trace.py:45 response_closed.complete
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 11] Max packet in: 32768 bytes
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 11] Max packet out: 32768 bytes
[35mDEBUG   [0m paramiko.transport:transport.py:1893 Secsh channel 11 opened.
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 11] Sesch channel 11 request ok
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 11] EOF received (11)
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 11] EOF sent (11)
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 12] Max packet in: 32768 bytes
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 12] Max packet out: 32768 bytes
[35mDEBUG   [0m paramiko.transport:transport.py:1893 Secsh channel 12 opened.
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 12] Sesch channel 12 request ok
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 12] EOF received (12)
[35mDEBUG   [0m paramiko.transport:channel.py:1210 [chan 12] EOF sent (12)